import type { Anime, AnimeEpisode, VideoSource } from '../types/anime';

// Helper to generate mock episodes with multi-quality streams
export const generateEpisodes = (animeId: number, _animeTitle: string, count: number): AnimeEpisode[] => {
  const episodes: AnimeEpisode[] = [];
  const titles = [
    'Kebangkitan Sang Pemburu Terkuat',
    'Pertemuan yang Ditakdirkan di Balik Kabut',
    'Ujian Mematikan di Kedalaman Dungeon',
    'Rahasia Kekuatan yang Terpendam',
    'Pertarungan Sengit di Wilayah Terlarang',
    'Pengorbanan dan Tekad Membara',
    'Bayangan Masa Lalu yang Menghantui',
    'Titik Balik Takdir',
    'Serangan Balik yang Tak Terduga',
    'Puncak Pertempuran Para Raja',
    'Cahaya Harapan Baru',
    'Menuju Era yang Berbeda',
    'Janji di Bawah Langit Berbintang',
    'Darah dan Air Mata',
    'Kebangkitan Raja Kegelapan',
    'Langkah Terakhir Menuju Keabadian',
    'Pertarungan Dua Takdir',
    'Kekuatan Sejati Tanpa Batas',
    'Badai Sebelum Ketenangan',
    'Akhir dari Permulaan',
    'Penebusan Dosa Masa Lalu',
    'Hati yang Tak Tertundukkan',
    'Pintu Menuju Dunia Lain',
    'Legenda Baru Telah Lahir'
  ];

  for (let i = 1; i <= count; i++) {
    const titleIndex = (i - 1) % titles.length;
    const epTitle = titles[titleIndex];

    const sources: VideoSource[] = [
      {
        quality: '1080p',
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        format: 'mp4',
        label: '1080p FHD (Ultra Clear)'
      },
      {
        quality: '720p',
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        format: 'mp4',
        label: '720p HD (Recommended)'
      },
      {
        quality: '480p',
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        format: 'mp4',
        label: '480p SD (Data Saver)'
      },
      {
        quality: '360p',
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        format: 'mp4',
        label: '360p (Hemat Kuota)'
      }
    ];

    episodes.push({
      id: animeId * 1000 + i,
      number: i,
      title: `Episode ${i}: ${epTitle}`,
      duration: '24:15',
      thumbnail: `https://images.unsplash.com/photo-${1578632767115 + (i * 37) % 500}?auto=format&fit=crop&w=600&q=80`,
      synopsis: `Di episode ${i}, tensi semakin memuncak saat pertempuran strategis dimulai. Strategi tak terduga mengubah jalannya konflik.`,
      sources,
      embedUrl: `https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=0`
    });
  }

  return episodes;
};

export const INITIAL_ANIMES: Anime[] = [
  {
    id: 1,
    title: 'Solo Leveling: Arise from the Shadow',
    japaneseTitle: '俺だけレベルアップな件',
    romajiTitle: 'Ore dake Level Up na Ken',
    synopsis: 'Lebih dari satu dekade telah berlalu sejak kemunculan "gates" misterius yang menghubungkan dunia manusia ke dimensi sarang monster. Sung Jin-woo, pemburu terlemah berperingkat E, secara ajaib terpilih oleh sistem "Quest" unik yang memungkinkan dirinya meningkatkan kekuatannya tanpa batas.',
    posterImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=85',
    score: 9.15,
    scoredBy: 842100,
    rank: 1,
    popularity: 1,
    status: 'Ongoing',
    episodesCount: 12,
    duration: '24 min per ep',
    season: 'Winter',
    year: 2024,
    genres: ['Action', 'Fantasy', 'Supernatural', 'Adventure'],
    studios: ['A-1 Pictures'],
    trailerUrl: 'https://www.youtube.com/watch?v=91t8n1R',
    ratingBadge: '17+',
    episodes: generateEpisodes(1, 'Solo Leveling', 12)
  },
  {
    id: 2,
    title: 'Sousou no Frieren (Frieren: Beyond Journey\'s End)',
    japaneseTitle: '葬送のフリーレン',
    romajiTitle: 'Sousou no Frieren',
    synopsis: 'Kelompok pahlawan telah mengalahkan Raja Iblis dan membawa perdamaian dunia. Namun bagi Frieren, seorang penyihir elf yang berumur ribuan tahun, petualangan 10 tahun itu hanyalah sekejap mata. Setelah teman-temannya menua dan meninggal, Frieren memulai perjalanan baru untuk memahami esensi emosi manusia.',
    posterImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=85',
    score: 9.38,
    scoredBy: 620000,
    rank: 2,
    popularity: 2,
    status: 'Completed',
    episodesCount: 28,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2023,
    genres: ['Adventure', 'Drama', 'Fantasy', 'Slice of Life'],
    studios: ['Madhouse'],
    ratingBadge: '13+',
    episodes: generateEpisodes(2, 'Sousou no Frieren', 28)
  },
  {
    id: 3,
    title: 'Jujutsu Kaisen Season 2 (Shibuya Incident)',
    japaneseTitle: '呪術廻戦',
    romajiTitle: 'Jujutsu Kaisen',
    synopsis: '31 Oktober, stasiun Shibuya yang ramai tiba-tiba terkurung oleh tirai kegelapan misterius. Puluhan ribu warga sipil disandera demi memancing penyihir terkuat di dunia, Satoru Gojo. Sebuah pertempuran kolosal yang menentukan nasib umat manusia meletus.',
    posterImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1600&q=85',
    score: 8.92,
    scoredBy: 910400,
    rank: 4,
    popularity: 3,
    status: 'Completed',
    episodesCount: 23,
    duration: '23 min per ep',
    season: 'Summer',
    year: 2023,
    genres: ['Action', 'Fantasy', 'Shounen', 'Supernatural'],
    studios: ['MAPPA'],
    ratingBadge: '17+',
    episodes: generateEpisodes(3, 'Jujutsu Kaisen Season 2', 23)
  },
  {
    id: 4,
    title: 'Attack on Titan: The Final Season',
    japaneseTitle: '進撃の巨人',
    romajiTitle: 'Shingeki no Kyojin',
    synopsis: 'Eren Yeager melancarkan The Rumbling untuk melenyapkan semua kehidupan di luar Pulau Paradis demi melindungi tanah kelahirannya. Teman-temannya di Survey Corps bersatu dengan musuh lama untuk menghentikan bencana kepunahan global dalam duel terakhir yang epik.',
    posterImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=85',
    score: 9.06,
    scoredBy: 1250000,
    rank: 3,
    popularity: 4,
    status: 'Completed',
    episodesCount: 28,
    duration: '24 min per ep',
    season: 'Winter',
    year: 2022,
    genres: ['Action', 'Drama', 'Mystery', 'Suspense'],
    studios: ['MAPPA'],
    ratingBadge: '17+',
    episodes: generateEpisodes(4, 'Attack on Titan', 28)
  },
  {
    id: 5,
    title: 'Demon Slayer: Hashira Training Arc',
    japaneseTitle: '鬼滅の刃 柱稽古編',
    romajiTitle: 'Kimetsu no Yaiba: Hashira Geiko-hen',
    synopsis: 'Menjelang pertempuran pamungkas melawan Kibutsuji Muzan di Kastil Tak Berhingga, seluruh anggota Korps Pembasmi Iblis menjalani pelatihan neraka bersama para Hashira terpilih untuk membangkitkan tanda iblis.',
    posterImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1600&q=85',
    score: 8.78,
    scoredBy: 530000,
    rank: 8,
    popularity: 5,
    status: 'Completed',
    episodesCount: 8,
    duration: '25 min per ep',
    season: 'Spring',
    year: 2024,
    genres: ['Action', 'Fantasy', 'Historical', 'Shounen'],
    studios: ['ufotable'],
    ratingBadge: '17+',
    episodes: generateEpisodes(5, 'Demon Slayer', 8)
  },
  {
    id: 6,
    title: 'One Piece (Egghead Arc)',
    japaneseTitle: 'ワンピース',
    romajiTitle: 'One Piece',
    synopsis: 'Monkey D. Luffy dan Topi Jerami mendarat di Egghead, pulau sains masa depan milik ilmuwan jenius Dr. Vegapunk. Namun rahasia terbesar Pemerintah Dunia dan Abad Kekosongan mulai terkuak hingga armada Angkatan Laut mengepung pulau.',
    posterImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=85',
    score: 8.95,
    scoredBy: 1540000,
    rank: 5,
    popularity: 6,
    status: 'Ongoing',
    episodesCount: 1110,
    duration: '24 min per ep',
    season: 'Fall',
    year: 1999,
    genres: ['Action', 'Adventure', 'Comedy', 'Fantasy'],
    studios: ['Toei Animation'],
    ratingBadge: '13+',
    episodes: generateEpisodes(6, 'One Piece', 24)
  },
  {
    id: 7,
    title: 'Chainsaw Man',
    japaneseTitle: 'チェンソーマン',
    romajiTitle: 'Chainsaw Man',
    synopsis: 'Denji hidup dalam kemiskinan ekstrem dan bekerja sebagai pemburu iblis untuk melunasi hutang ayahnya. Setelah dikhianati dan dibunuh, iblis gergaji kesayangannya, Pochita, menyatu dengan jantungnya dan melahirkan manusia gergaji.',
    posterImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1600&q=85',
    score: 8.52,
    scoredBy: 780000,
    rank: 12,
    popularity: 7,
    status: 'Completed',
    episodesCount: 12,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2022,
    genres: ['Action', 'Supernatural', 'Gore', 'Shounen'],
    studios: ['MAPPA'],
    ratingBadge: '17+',
    episodes: generateEpisodes(7, 'Chainsaw Man', 12)
  },
  {
    id: 8,
    title: 'Oshi no Ko Season 2',
    japaneseTitle: '【推しの子】第2期',
    romajiTitle: 'Oshi no Ko 2nd Season',
    synopsis: 'Aqua Hoshino menyelami dunia teater drama 2.5D untuk mengungkap dalang di balik kematian idol legendaris Ai Hoshino. Di atas panggung, intrik kepalsuan dan emosi mendalam saling bertubrukan.',
    posterImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=85',
    score: 8.68,
    scoredBy: 410000,
    rank: 10,
    popularity: 8,
    status: 'Ongoing',
    episodesCount: 13,
    duration: '24 min per ep',
    season: 'Summer',
    year: 2024,
    genres: ['Drama', 'Mystery', 'Psychological'],
    studios: ['Doga Kobo'],
    ratingBadge: '13+',
    episodes: generateEpisodes(8, 'Oshi no Ko', 13)
  },
  {
    id: 9,
    title: 'Bleach: Thousand-Year Blood War',
    japaneseTitle: 'BLEACH 千年血戦篇',
    romajiTitle: 'Bleach: Sennen Kessen-hen',
    synopsis: 'Perang suci antara Shinigami dan Quincy kembali pecah setelah ribuan tahun tertidur. Yhwach memimpin pasukan Sternritter menyerbu Soul Society dengan kekuatan yang tak terbayangkan.',
    posterImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1600&q=85',
    score: 9.02,
    scoredBy: 490000,
    rank: 6,
    popularity: 9,
    status: 'Ongoing',
    episodesCount: 26,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2022,
    genres: ['Action', 'Adventure', 'Fantasy', 'Shounen'],
    studios: ['Pierrot'],
    ratingBadge: '17+',
    episodes: generateEpisodes(9, 'Bleach: TYBW', 26)
  },
  {
    id: 10,
    title: 'Bocchi the Rock!',
    japaneseTitle: 'ぼっち・ざ・ろっく！',
    romajiTitle: 'Bocchi the Rock!',
    synopsis: 'Hitori Gotoh adalah gadis introver pemalu yang bermimpi memiliki band rock. Tak disangka, pertemuannya dengan Nijika membawanya bergabung dengan Kessoku Band dan mengubah hidupnya yang sunyi menjadi penuh nada.',
    posterImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=85',
    score: 8.81,
    scoredBy: 390000,
    rank: 9,
    popularity: 10,
    status: 'Completed',
    episodesCount: 12,
    duration: '23 min per ep',
    season: 'Fall',
    year: 2022,
    genres: ['Comedy', 'Music', 'Slice of Life'],
    studios: ['CloverWorks'],
    ratingBadge: '13+',
    episodes: generateEpisodes(10, 'Bocchi the Rock!', 12)
  },
  {
    id: 11,
    title: 'Cyberpunk: Edgerunners',
    japaneseTitle: 'サイバーパンク エッジランナーズ',
    romajiTitle: 'Cyberpunk: Edgerunners',
    synopsis: 'Di kota futuristik Night City yang dipenuhi korupsi dan modifikasi cybernetic, seorang anak jalanan berbakat memilih jalan sebagai Edgerunner, tentara bayaran di luar hukum yang siap bertaruh nyawa.',
    posterImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1600&q=85',
    score: 8.62,
    scoredBy: 680000,
    rank: 14,
    popularity: 11,
    status: 'Completed',
    episodesCount: 10,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2022,
    genres: ['Action', 'Sci-Fi', 'Gore', 'Psychological'],
    studios: ['Trigger'],
    ratingBadge: '18+',
    episodes: generateEpisodes(11, 'Cyberpunk: Edgerunners', 10)
  },
  {
    id: 12,
    title: 'Dandadan',
    japaneseTitle: 'ダンダダン',
    romajiTitle: 'Dandadan',
    synopsis: 'Momo Ayase yang percaya pada hantu tapi tidak pada alien bertemu dengan Okarun yang percaya pada alien tapi tidak pada hantu. Taruhan konyol mereka menyeret keduanya ke dalam pusaran fenomena paranormal yang gila dan seru.',
    posterImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=85',
    score: 8.74,
    scoredBy: 320000,
    rank: 11,
    popularity: 12,
    status: 'Ongoing',
    episodesCount: 12,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2024,
    genres: ['Action', 'Comedy', 'Supernatural', 'Sci-Fi'],
    studios: ['Science SARU'],
    ratingBadge: '17+',
    episodes: generateEpisodes(12, 'Dandadan', 12)
  },
  {
    id: 13,
    title: 'Death Note',
    japaneseTitle: 'デスノート',
    romajiTitle: 'Death Note',
    synopsis: 'Light Yagami, siswa jenius di Jepang, menemukan buku catatan supranatural milik Shinigami. Setiap orang yang namanya tertulis di buku tersebut akan mati. Perang pikiran antara Light dan detektif jenius L pun dimulai.',
    posterImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=85',
    score: 8.62,
    scoredBy: 2800000,
    rank: 15,
    popularity: 13,
    status: 'Completed',
    episodesCount: 37,
    duration: '23 min per ep',
    season: 'Fall',
    year: 2006,
    genres: ['Mystery', 'Psychological', 'Supernatural', 'Suspense'],
    studios: ['Madhouse'],
    ratingBadge: '17+',
    episodes: generateEpisodes(13, 'Death Note', 37)
  },
  {
    id: 14,
    title: 'Fullmetal Alchemist: Brotherhood',
    japaneseTitle: '鋼の錬金術師 FULLMETAL ALCHEMIST',
    romajiTitle: 'Hagane no Renkinjutsushi',
    synopsis: 'Dua bersaudara Edward dan Alphonse Elric melanggar tabu terbesar alkimia untuk menghidupkan kembali ibu mereka. Demi mengembalikan tubuh mereka yang hilang, mereka mengembara mencari Batu Bertuah legendaris.',
    posterImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1600&q=85',
    score: 9.10,
    scoredBy: 2200000,
    rank: 2,
    popularity: 14,
    status: 'Completed',
    episodesCount: 64,
    duration: '24 min per ep',
    season: 'Spring',
    year: 2009,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy'],
    studios: ['Bones'],
    ratingBadge: '17+',
    episodes: generateEpisodes(14, 'Fullmetal Alchemist: Brotherhood', 64)
  },
  {
    id: 15,
    title: 'Hunter x Hunter (2011)',
    japaneseTitle: 'ハンター×ハンター',
    romajiTitle: 'Hunter x Hunter',
    synopsis: 'Gon Freecss bercita-cita menjadi Hunter profesional untuk menemukan ayahnya yang seorang Hunter legendaris. Bersama Killua, Kurapika, dan Leorio, ia menghadapi ujian mematikan dan dunia Nen yang misterius.',
    posterImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=85',
    score: 9.04,
    scoredBy: 1800000,
    rank: 7,
    popularity: 15,
    status: 'Completed',
    episodesCount: 148,
    duration: '23 min per ep',
    season: 'Fall',
    year: 2011,
    genres: ['Action', 'Adventure', 'Fantasy', 'Shounen'],
    studios: ['Madhouse'],
    ratingBadge: '13+',
    episodes: generateEpisodes(15, 'Hunter x Hunter', 24)
  },
  {
    id: 16,
    title: 'Kaguya-sama: Love Is War - Ultra Romantic',
    japaneseTitle: 'かぐや様は告らせたい',
    romajiTitle: 'Kaguya-sama wa Kokurasetai',
    synopsis: 'Miyuki Shirogane dan Kaguya Shinomiya adalah dua siswa paling elit di Akademi Shuchiin. Saling menyukai namun terlalu gengsi untuk mengaku, mereka menganggap cinta sebagai perang: siapa yang menyatakan cinta duluan, dialah yang kalah!',
    posterImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=85',
    score: 8.98,
    scoredBy: 520000,
    rank: 6,
    popularity: 16,
    status: 'Completed',
    episodesCount: 13,
    duration: '23 min per ep',
    season: 'Spring',
    year: 2022,
    genres: ['Comedy', 'Romance', 'Psychological', 'School'],
    studios: ['A-1 Pictures'],
    ratingBadge: '13+',
    episodes: generateEpisodes(16, 'Kaguya-sama', 13)
  },
  {
    id: 17,
    title: 'Mushoku Tensei: Jobless Reincarnation Season 2',
    japaneseTitle: '無職転生 ～異世界行ったら本気だす～',
    romajiTitle: 'Mushoku Tensei: Isekai Ittara Honki Dasu',
    synopsis: 'Seorang pria pengangguran berusia 34 tahun bereinkarnasi sebagai bayi bernama Rudeus Greyrat di dunia pedang dan sihir. Berbekal kenangan kehidupan masa lalunya, ia bertekad menjalani hidup barunya dengan sungguh-sungguh tanpa penyesalan.',
    posterImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=85',
    score: 8.71,
    scoredBy: 390000,
    rank: 13,
    popularity: 17,
    status: 'Ongoing',
    episodesCount: 24,
    duration: '23 min per ep',
    season: 'Spring',
    year: 2024,
    genres: ['Adventure', 'Drama', 'Fantasy', 'Isekai'],
    studios: ['Studio Bind'],
    ratingBadge: '17+',
    episodes: generateEpisodes(17, 'Mushoku Tensei', 24)
  },
  {
    id: 18,
    title: 'Steins;Gate',
    japaneseTitle: 'シュタインズ・ゲート',
    romajiTitle: 'Steins;Gate',
    synopsis: 'Rintaro Okabe, ilmuwan gila eksentrik, tanpa sengaja menemukan cara mengirim pesan teks ke masa lalu menggunakan oven microwave yang dimodifikasi. Eksperimen ini memicu rangkaian manipulasi garis waktu yang membawa konsekuensi maut.',
    posterImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1600&q=85',
    score: 9.07,
    scoredBy: 1400000,
    rank: 3,
    popularity: 18,
    status: 'Completed',
    episodesCount: 24,
    duration: '24 min per ep',
    season: 'Spring',
    year: 2011,
    genres: ['Drama', 'Sci-Fi', 'Suspense', 'Psychological'],
    studios: ['White Fox'],
    ratingBadge: '17+',
    episodes: generateEpisodes(18, 'Steins;Gate', 24)
  },
  {
    id: 19,
    title: 'Spy x Family Season 2',
    japaneseTitle: 'SPY×FAMILY',
    romajiTitle: 'Spy x Family',
    synopsis: 'Mata-mata handal Twilight harus membangun keluarga samaran demi misi perdamaian dunia. Tanpa ia ketahui, istri yang dinikahinya adalah pembunuh bayaran ulung, dan putri angkatnya adalah gadis telepati yang bisa membaca pikiran.',
    posterImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=85',
    score: 8.24,
    scoredBy: 590000,
    rank: 22,
    popularity: 19,
    status: 'Completed',
    episodesCount: 12,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2023,
    genres: ['Action', 'Comedy', 'Slice of Life'],
    studios: ['WIT Studio', 'CloverWorks'],
    ratingBadge: '13+',
    episodes: generateEpisodes(19, 'Spy x Family', 12)
  },
  {
    id: 20,
    title: 'Vinland Saga Season 2',
    japaneseTitle: 'ヴィンランド・サガ',
    romajiTitle: 'Vinland Saga',
    synopsis: 'Thorfinn yang kehilangan tujuan hidup setelah kematian Askeladd kini bekerja sebagai budak di tanah pertanian Ketil. Di tengah kehampaan jiwanya, ia memulai perjalanan filosofis untuk memahami arti sejati dari seorang pejuang tanpa pedang.',
    posterImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1600&q=85',
    score: 8.84,
    scoredBy: 460000,
    rank: 8,
    popularity: 20,
    status: 'Completed',
    episodesCount: 24,
    duration: '24 min per ep',
    season: 'Winter',
    year: 2023,
    genres: ['Action', 'Adventure', 'Drama', 'Historical'],
    studios: ['MAPPA'],
    ratingBadge: '17+',
    episodes: generateEpisodes(20, 'Vinland Saga', 24)
  },
  {
    id: 21,
    title: 'Violet Evergarden',
    japaneseTitle: 'ヴァイオレット・エヴァーガーデン',
    romajiTitle: 'Violet Evergarden',
    synopsis: 'Mantan tentara anak perempuan yang hanya mengenal medan perang kini bekerja sebagai Auto Memory Doll yang mengetik surat emosional bagi orang lain, demi mengungkap arti kata terakhir dari Mayor Gilbert: "Aku mencintaimu".',
    posterImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=85',
    score: 8.67,
    scoredBy: 980000,
    rank: 16,
    popularity: 21,
    status: 'Completed',
    episodesCount: 13,
    duration: '24 min per ep',
    season: 'Winter',
    year: 2018,
    genres: ['Drama', 'Fantasy', 'Slice of Life'],
    studios: ['Kyoto Animation'],
    ratingBadge: '13+',
    episodes: generateEpisodes(21, 'Violet Evergarden', 13)
  },
  {
    id: 22,
    title: 'Wind Breaker',
    japaneseTitle: 'ウィンドブレイカー',
    romajiTitle: 'Wind Breaker',
    synopsis: 'Haruka Sakura datang ke SMA Furin dengan satu tujuan: mengalahkan semua orang dan menjadi yang terkuat di puncak sekolah preman. Namun ia terkejut saat mengetahui murid Furin justru menjadi pelindung kota yang dicintai warga.',
    posterImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=85',
    score: 7.92,
    scoredBy: 180000,
    rank: 45,
    popularity: 22,
    status: 'Completed',
    episodesCount: 12,
    duration: '23 min per ep',
    season: 'Spring',
    year: 2024,
    genres: ['Action', 'Delinquents', 'School'],
    studios: ['CloverWorks'],
    ratingBadge: '13+',
    episodes: generateEpisodes(22, 'Wind Breaker', 12)
  },
  {
    id: 23,
    title: 'Yu Yu Hakusho',
    japaneseTitle: '幽☆遊☆白書',
    romajiTitle: 'Yu Yu Hakusho',
    synopsis: 'Yusuke Urameshi, remaja pembuat onar berusia 14 tahun, tewas setelah menyelamatkan seorang anak kecil dari tabrakan mobil. Tindakan altruistiknya mengejutkan Dunia Roh, dan ia diberi kesempatan hidup kembali sebagai Detektif Roh.',
    posterImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1600&q=85',
    score: 8.44,
    scoredBy: 580000,
    rank: 25,
    popularity: 23,
    status: 'Completed',
    episodesCount: 112,
    duration: '24 min per ep',
    season: 'Fall',
    year: 1992,
    genres: ['Action', 'Comedy', 'Supernatural', 'Martial Arts'],
    studios: ['Pierrot'],
    ratingBadge: '13+',
    episodes: generateEpisodes(23, 'Yu Yu Hakusho', 24)
  },
  {
    id: 24,
    title: 'Zom 100: Bucket List of the Dead',
    japaneseTitle: 'ゾン100～ゾンビになるまでにしたい100のこと～',
    romajiTitle: 'Zom 100: Zombie ni Naru made ni Shitai 100 no Koto',
    synopsis: 'Akira Tendo menderita selama 3 tahun bekerja di perusahaan eksploitatif yang menghancurkan jiwanya. Ketika wabah zombie mendadak menghancurkan Tokyo, alih-alih panik, Akira justru bersorak gembira karena tidak perlu lagi masuk kantor!',
    posterImage: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=85',
    coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=85',
    score: 7.85,
    scoredBy: 240000,
    rank: 52,
    popularity: 24,
    status: 'Completed',
    episodesCount: 12,
    duration: '24 min per ep',
    season: 'Summer',
    year: 2023,
    genres: ['Action', 'Comedy', 'Horror', 'Supernatural'],
    studios: ['BUG FILMS'],
    ratingBadge: '17+',
    episodes: generateEpisodes(24, 'Zom 100', 12)
  }
];

export const GENRES_LIST = [
  'All Genres',
  'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Fantasy',
  'Gore',
  'Historical',
  'Isekai',
  'Music',
  'Mystery',
  'Psychological',
  'Romance',
  'Sci-Fi',
  'School',
  'Shounen',
  'Slice of Life',
  'Supernatural',
  'Suspense'
];
