import type { Anime, AnimeEpisode, VideoSource } from '../types/anime';

// Helper to generate anime episodes
export const generateEpisodes = (
  animeId: number,
  animeTitle: string,
  count: number,
  fallbackThumbnail?: string
): AnimeEpisode[] => {
  const episodes: AnimeEpisode[] = [];

  for (let i = 1; i <= count; i++) {
    const sources: VideoSource[] = [
      {
        quality: '1080p',
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        format: 'mp4',
        label: '1080p FHD (Ultra Clear)'
      },
      {
        quality: '720p',
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        format: 'mp4',
        label: '720p HD (Recommended)'
      },
      {
        quality: '480p',
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        format: 'mp4',
        label: '480p SD (Data Saver)'
      },
      {
        quality: '360p',
        url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        format: 'mp4',
        label: '360p (Hemat Kuota)'
      }
    ];

    episodes.push({
      id: animeId * 1000 + i,
      number: i,
      title: `Episode ${i}`,
      duration: '24:00',
      thumbnail: fallbackThumbnail || 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-it355ZgzquUd.png',
      synopsis: `Tonton ${animeTitle} Episode ${i} dengan takarir / subtitle Indonesia dan resolusi Full HD 1080p di DKanime.`,
      sources,
      embedUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=0'
    });
  }

  return episodes;
};

// Helper to generate a single full-length Movie entry
export const generateMovieEpisode = (
  animeId: number,
  animeTitle: string,
  durationStr: string,
  coverImage: string,
  trailerId?: string
): AnimeEpisode[] => {
  const embedUrl = trailerId
    ? `https://www.youtube.com/embed/${trailerId}?autoplay=0`
    : 'https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=0';

  return [
    {
      id: animeId * 1000 + 1,
      number: 1,
      title: `Film Penuh: ${animeTitle}`,
      duration: durationStr,
      thumbnail: coverImage,
      synopsis: `Tonton film layar lebar penuh ${animeTitle} kualitas Full HD 1080p dengan audio jernih dan takarir / subtitle Indonesia di DKanime.`,
      sources: [
        {
          quality: '1080p',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
          format: 'mp4',
          label: '1080p FHD (Ultra Clear)'
        },
        {
          quality: '720p',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
          format: 'mp4',
          label: '720p HD (Recommended)'
        },
        {
          quality: '480p',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
          format: 'mp4',
          label: '480p SD (Data Saver)'
        }
      ],
      embedUrl
    }
  ];
};

export const INITIAL_ANIMES: Anime[] = [
  {
    id: 1,
    title: 'Solo Leveling: Arise from the Shadow',
    japaneseTitle: '俺だけレベルアップな件',
    romajiTitle: 'Ore dake Level Up na Ken',
    synopsis: 'Lebih dari satu dekade telah berlalu sejak kemunculan "gates" misterius yang menghubungkan dunia manusia ke dimensi sarang monster. Sung Jin-woo, pemburu terlemah berperingkat E, secara ajaib terpilih oleh sistem "Quest" unik yang memungkinkan dirinya meningkatkan kekuatannya tanpa batas.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-it355ZgzquUd.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/151807-37yfQA3ym8PA.jpg',
    score: 8,
    scoredBy: 842100,
    rank: 1,
    popularity: 1,format: 'TV',
    
    status: 'Ongoing',
    episodesCount: 12,
    duration: '24 min per ep',
    season: 'Winter',
    year: 2024,
    genres: ['Action', 'Fantasy', 'Supernatural', 'Adventure'],
    studios: ['A-1 Pictures'],
    trailerUrl: 'https://www.youtube.com/watch?v=91t8n1R',
    ratingBadge: '17+',
    episodes: generateEpisodes(1, 'Solo Leveling', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/151807-37yfQA3ym8PA.jpg')
  },
  {
    id: 2,
    title: 'Sousou no Frieren (Frieren: Beyond Journey\'s End)',
    japaneseTitle: '葬送のフリーレン',
    romajiTitle: 'Sousou no Frieren',
    synopsis: 'Kelompok pahlawan telah mengalahkan Raja Iblis dan membawa perdamaian dunia. Namun bagi Frieren, seorang penyihir elf yang berumur ribuan tahun, petualangan 10 tahun itu hanyalah sekejap mata. Setelah teman-temannya menua dan meninggal, Frieren memulai perjalanan baru untuk memahami esensi emosi manusia.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154587-qQTzQnEJJ3oB.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/154587-ivXNJ23SM1xB.jpg',
    score: 9.1,
    scoredBy: 620000,
    rank: 2,
    popularity: 2,format: 'TV',
    
    status: 'Completed',
    episodesCount: 28,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2023,
    genres: ['Adventure', 'Drama', 'Fantasy', 'Slice of Life'],
    studios: ['Madhouse'],
    ratingBadge: '13+',
    episodes: generateEpisodes(2, 'Sousou no Frieren', 28, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/154587-ivXNJ23SM1xB.jpg')
  },
  {
    id: 3,
    title: 'Jujutsu Kaisen Season 2 (Shibuya Incident)',
    japaneseTitle: '呪術廻戦 第2期',
    romajiTitle: 'Jujutsu Kaisen 2nd Season',
    synopsis: '31 Oktober, stasiun Shibuya yang ramai tiba-tiba terkurung oleh tirai kegelapan misterius. Puluhan ribu warga sipil disandera demi memancing penyihir terkuat di dunia, Satoru Gojo. Sebuah pertempuran kolosal yang menentukan nasib umat manusia meletus.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx145064-hSNRJM03pvv1.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/145064-esDtAY2He7sk.jpg',
    score: 8.6,
    scoredBy: 910400,
    rank: 4,
    popularity: 3,format: 'TV',
    
    status: 'Completed',
    episodesCount: 23,
    duration: '23 min per ep',
    season: 'Summer',
    year: 2023,
    genres: ['Action', 'Fantasy', 'Shounen', 'Supernatural'],
    studios: ['MAPPA'],
    ratingBadge: '17+',
    episodes: generateEpisodes(3, 'Jujutsu Kaisen Season 2', 23, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/145064-esDtAY2He7sk.jpg')
  },
  {
    id: 4,
    title: 'Attack on Titan: The Final Season',
    japaneseTitle: '進撃の巨人',
    romajiTitle: 'Shingeki no Kyojin',
    synopsis: 'Eren Yeager melancarkan The Rumbling untuk melenyapkan semua kehidupan di luar Pulau Paradis demi melindungi tanah kelahirannya. Teman-temannya di Survey Corps bersatu dengan musuh lama untuk menghentikan bencana kepunahan global dalam duel terakhir yang epik.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-buvcRTBx4NSm.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8jpFCOcDmneX.jpg',
    score: 8.5,
    scoredBy: 1250000,
    rank: 3,
    popularity: 4,format: 'TV',
    
    status: 'Completed',
    episodesCount: 28,
    duration: '24 min per ep',
    season: 'Winter',
    year: 2022,
    genres: ['Action', 'Drama', 'Mystery', 'Suspense'],
    studios: ['MAPPA'],
    ratingBadge: '17+',
    episodes: generateEpisodes(4, 'Attack on Titan', 28, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8jpFCOcDmneX.jpg')
  },
  {
    id: 5,
    title: 'Demon Slayer: Hashira Training Arc',
    japaneseTitle: '鬼滅の刃',
    romajiTitle: 'Kimetsu no Yaiba',
    synopsis: 'Menjelang pertempuran pamungkas melawan Kibutsuji Muzan di Kastil Tak Berhingga, seluruh anggota Korps Pembasmi Iblis menjalani pelatihan neraka bersama para Hashira terpilih untuk membangkitkan tanda iblis.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-WBsBl0ClmgYL.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-33MtJGsUSxga.jpg',
    score: 8.3,
    scoredBy: 530000,
    rank: 8,
    popularity: 5,format: 'TV',
    
    status: 'Completed',
    episodesCount: 8,
    duration: '25 min per ep',
    season: 'Spring',
    year: 2024,
    genres: ['Action', 'Fantasy', 'Historical', 'Shounen'],
    studios: ['ufotable'],
    ratingBadge: '17+',
    episodes: generateEpisodes(5, 'Demon Slayer', 8, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-33MtJGsUSxga.jpg')
  },
  {
    id: 6,
    title: 'One Piece (Egghead Arc)',
    japaneseTitle: 'ONE PIECE',
    romajiTitle: 'ONE PIECE',
    synopsis: 'Monkey D. Luffy dan Topi Jerami mendarat di Egghead, pulau sains masa depan milik ilmuwan jenius Dr. Vegapunk. Namun rahasia terbesar Pemerintah Dunia dan Abad Kekosongan mulai terkuak hingga armada Angkatan Laut mengepung pulau.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21-ELSYx3yMPcKM.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg',
    score: 8.7,
    scoredBy: 1540000,
    rank: 5,
    popularity: 6,format: 'TV',
    
    status: 'Ongoing',
    episodesCount: 1110,
    duration: '24 min per ep',
    season: 'Fall',
    year: 1999,
    genres: ['Action', 'Adventure', 'Comedy', 'Fantasy'],
    studios: ['Toei Animation'],
    ratingBadge: '13+',
    episodes: generateEpisodes(6, 'One Piece', 24, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg')
  },
  {
    id: 7,
    title: 'Chainsaw Man',
    japaneseTitle: 'チェンソーマン',
    romajiTitle: 'Chainsaw Man',
    synopsis: 'Denji hidup dalam kemiskinan ekstrem dan bekerja sebagai pemburu iblis untuk melunasi hutang ayahnya. Setelah dikhianati dan dibunuh, iblis gergaji kesayangannya, Pochita, menyatu dengan jantungnya dan melahirkan manusia gergaji.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx127230-DdP4vAdssLoz.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/127230-o8IRwCGVr9KW.jpg',
    score: 8.3,
    scoredBy: 780000,
    rank: 12,
    popularity: 7,format: 'TV',
    
    status: 'Completed',
    episodesCount: 12,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2022,
    genres: ['Action', 'Supernatural', 'Gore', 'Shounen'],
    studios: ['MAPPA'],
    ratingBadge: '17+',
    episodes: generateEpisodes(7, 'Chainsaw Man', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/127230-o8IRwCGVr9KW.jpg')
  },
  {
    id: 8,
    title: 'Oshi no Ko Season 2',
    japaneseTitle: '【推しの子】',
    romajiTitle: '[Oshi no Ko]',
    synopsis: 'Aqua Hoshino menyelami dunia teater drama 2.5D untuk mengungkap dalang di balik kematian idol legendaris Ai Hoshino. Di atas panggung, intrik kepalsuan dan emosi mendalam saling bertubrukan.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx150672-WqmmwZ4nMzAy.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/150672-ISwoA0eS722H.jpg',
    score: 8.4,
    scoredBy: 410000,
    rank: 10,
    popularity: 8,format: 'TV',
    
    status: 'Ongoing',
    episodesCount: 13,
    duration: '24 min per ep',
    season: 'Summer',
    year: 2024,
    genres: ['Drama', 'Mystery', 'Psychological'],
    studios: ['Doga Kobo'],
    ratingBadge: '13+',
    episodes: generateEpisodes(8, 'Oshi no Ko', 13, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/150672-ISwoA0eS722H.jpg')
  },
  {
    id: 9,
    title: 'Bleach: Thousand-Year Blood War',
    japaneseTitle: 'BLEACH 千年血戦篇',
    romajiTitle: 'BLEACH: Sennen Kessen-hen',
    synopsis: 'Perang suci antara Shinigami dan Quincy kembali pecah setelah ribuan tahun tertidur. Yhwach memimpin pasukan Sternritter menyerbu Soul Society dengan kekuatan yang tak terbayangkan.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx116674-p3zK4PUX2Aag.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/116674-l2YlIyJzvGSV.jpg',
    score: 8.8,
    scoredBy: 490000,
    rank: 6,
    popularity: 9,format: 'TV',
    
    status: 'Ongoing',
    episodesCount: 26,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2022,
    genres: ['Action', 'Adventure', 'Fantasy', 'Shounen'],
    studios: ['Pierrot'],
    ratingBadge: '17+',
    episodes: generateEpisodes(9, 'Bleach: TYBW', 26, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/116674-l2YlIyJzvGSV.jpg')
  },
  {
    id: 10,
    title: 'Bocchi the Rock!',
    japaneseTitle: 'ぼっち・ざ・ろっく！',
    romajiTitle: 'Bocchi the Rock!',
    synopsis: 'Hitori Gotoh adalah gadis introver pemalu yang bermimpi memiliki band rock. Tak disangka, pertemuannya dengan Nijika membawanya bergabung dengan Kessoku Band dan mengubah hidupnya yang sunyi menjadi penuh nada.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx130003-HTDmeL4RGeJ4.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/130003-5F90a7BtsPQN.jpg',
    score: 8.7,
    scoredBy: 390000,
    rank: 9,
    popularity: 10,format: 'TV',
    
    status: 'Completed',
    episodesCount: 12,
    duration: '23 min per ep',
    season: 'Fall',
    year: 2022,
    genres: ['Comedy', 'Music', 'Slice of Life'],
    studios: ['CloverWorks'],
    ratingBadge: '13+',
    episodes: generateEpisodes(10, 'Bocchi the Rock!', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/130003-5F90a7BtsPQN.jpg')
  },
  {
    id: 11,
    title: 'Cyberpunk: Edgerunners',
    japaneseTitle: 'サイバーパンク エッジランナーズ',
    romajiTitle: 'Cyberpunk: Edgerunners',
    synopsis: 'Di kota futuristik Night City yang dipenuhi korupsi dan modifikasi cybernetic, seorang anak jalanan berbakat memilih jalan sebagai Edgerunner, tentara bayaran di luar hukum yang siap bertaruh nyawa.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx120377-ayZPoxiWt4Li.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/120377-c15oLS8CA31s.jpg',
    score: 8.5,
    scoredBy: 680000,
    rank: 14,
    popularity: 11,format: 'TV',
    
    status: 'Completed',
    episodesCount: 10,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2022,
    genres: ['Action', 'Sci-Fi', 'Gore', 'Psychological'],
    studios: ['Trigger'],
    ratingBadge: '18+',
    episodes: generateEpisodes(11, 'Cyberpunk: Edgerunners', 10, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/120377-c15oLS8CA31s.jpg')
  },
  {
    id: 12,
    title: 'Dandadan',
    japaneseTitle: 'ダンダダン',
    romajiTitle: 'Dandadan',
    synopsis: 'Momo Ayase yang percaya pada hantu tapi tidak pada alien bertemu dengan Okarun yang percaya pada alien tapi tidak pada hantu. Taruhan konyol mereka menyeret keduanya ke dalam pusaran fenomena paranormal yang gila dan seru.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx171018-60q1B6GK2Ghb.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/171018-SpwPNAduszXl.jpg',
    score: 8.3,
    scoredBy: 320000,
    rank: 11,
    popularity: 12,format: 'TV',
    
    status: 'Ongoing',
    episodesCount: 12,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2024,
    genres: ['Action', 'Comedy', 'Supernatural', 'Sci-Fi'],
    studios: ['Science SARU'],
    ratingBadge: '17+',
    episodes: generateEpisodes(12, 'Dandadan', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/171018-SpwPNAduszXl.jpg')
  },
  {
    id: 13,
    title: 'Death Note',
    japaneseTitle: 'DEATH NOTE',
    romajiTitle: 'DEATH NOTE',
    synopsis: 'Light Yagami, siswa jenius di Jepang, menemukan buku catatan supranatural milik Shinigami. Setiap orang yang namanya tertulis di buku tersebut akan mati. Perang pikiran antara Light dan detektif jenius L pun dimulai.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-kUgkcrfOrkUM.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/1535.jpg',
    score: 8.4,
    scoredBy: 2800000,
    rank: 15,
    popularity: 13,format: 'TV',
    
    status: 'Completed',
    episodesCount: 37,
    duration: '23 min per ep',
    season: 'Fall',
    year: 2006,
    genres: ['Mystery', 'Psychological', 'Supernatural', 'Suspense'],
    studios: ['Madhouse'],
    ratingBadge: '17+',
    episodes: generateEpisodes(13, 'Death Note', 37, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/1535.jpg')
  },
  {
    id: 14,
    title: 'Fullmetal Alchemist: Brotherhood',
    japaneseTitle: '鋼の錬金術師 FULLMETAL ALCHEMIST',
    romajiTitle: 'Hagane no Renkinjutsushi: FULLMETAL ALCHEMIST',
    synopsis: 'Dua bersaudara Edward dan Alphonse Elric melanggar tabu terbesar alkimia untuk menghidupkan kembali ibu mereka. Demi mengembalikan tubuh mereka yang hilang, mereka mengembara mencari Batu Bertuah legendaris.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx5114-nSWCgQlmOMtj.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/5114-q0V5URebphSG.jpg',
    score: 9,
    scoredBy: 2200000,
    rank: 2,
    popularity: 14,format: 'TV',
    
    status: 'Completed',
    episodesCount: 64,
    duration: '24 min per ep',
    season: 'Spring',
    year: 2009,
    genres: ['Action', 'Adventure', 'Drama', 'Fantasy'],
    studios: ['Bones'],
    ratingBadge: '17+',
    episodes: generateEpisodes(14, 'Fullmetal Alchemist: Brotherhood', 64, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/5114-q0V5URebphSG.jpg')
  },
  {
    id: 15,
    title: 'Hunter x Hunter (2011)',
    japaneseTitle: 'HUNTER×HUNTER (2011)',
    romajiTitle: 'HUNTER×HUNTER (2011)',
    synopsis: 'Gon Freecss bercita-cita menjadi Hunter profesional untuk menemukan ayahnya yang seorang Hunter legendaris. Bersama Killua, Kurapika, dan Leorio, ia menghadapi ujian mematikan dan dunia Nen yang misterius.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-y5gsT1hoHuHw.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/11061-8WkkTZ6duKpq.jpg',
    score: 8.9,
    scoredBy: 1800000,
    rank: 7,
    popularity: 15,format: 'TV',
    
    status: 'Completed',
    episodesCount: 148,
    duration: '23 min per ep',
    season: 'Fall',
    year: 2011,
    genres: ['Action', 'Adventure', 'Fantasy', 'Shounen'],
    studios: ['Madhouse'],
    ratingBadge: '13+',
    episodes: generateEpisodes(15, 'Hunter x Hunter', 24, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/11061-8WkkTZ6duKpq.jpg')
  },
  {
    id: 16,
    title: 'Kaguya-sama: Love Is War - Ultra Romantic',
    japaneseTitle: 'かぐや様は告らせたい-ウルトラロマンティック-',
    romajiTitle: 'Kaguya-sama wa Kokurasetai: Ultra Romantic',
    synopsis: 'Miyuki Shirogane dan Kaguya Shinomiya adalah dua siswa paling elit di Akademi Shuchiin. Saling menyukai namun terlalu gengsi untuk mengaku, mereka menganggap cinta sebagai perang: siapa yang menyatakan cinta duluan, dialah yang kalah!',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx125367-1yuq9NFcQuLI.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/125367-hGPJLSNfprO3.jpg',
    score: 8.9,
    scoredBy: 520000,
    rank: 6,
    popularity: 16,format: 'TV',
    
    status: 'Completed',
    episodesCount: 13,
    duration: '23 min per ep',
    season: 'Spring',
    year: 2022,
    genres: ['Comedy', 'Romance', 'Psychological', 'School'],
    studios: ['A-1 Pictures'],
    ratingBadge: '13+',
    episodes: generateEpisodes(16, 'Kaguya-sama', 13, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/125367-hGPJLSNfprO3.jpg')
  },
  {
    id: 17,
    title: 'Mushoku Tensei: Jobless Reincarnation Season 2',
    japaneseTitle: '無職転生Ⅱ ～異世界行ったら本気だす～',
    romajiTitle: 'Mushoku Tensei II: Isekai Ittara Honki Dasu',
    synopsis: 'Seorang pria pengangguran berusia 34 tahun bereinkarnasi sebagai bayi bernama Rudeus Greyrat di dunia pedang dan sihir. Berbekal kenangan kehidupan masa lalunya, ia bertekad menjalani hidup barunya dengan sungguh-sungguh tanpa penyesalan.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx146065-IjirxRK26O03.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/146065-33RDijfuxLLk.jpg',
    score: 8.1,
    scoredBy: 390000,
    rank: 13,
    popularity: 17,format: 'TV',
    
    status: 'Ongoing',
    episodesCount: 24,
    duration: '23 min per ep',
    season: 'Spring',
    year: 2024,
    genres: ['Adventure', 'Drama', 'Fantasy', 'Isekai'],
    studios: ['Studio Bind'],
    ratingBadge: '17+',
    episodes: generateEpisodes(17, 'Mushoku Tensei', 24, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/146065-33RDijfuxLLk.jpg')
  },
  {
    id: 18,
    title: 'Steins;Gate',
    japaneseTitle: 'シュタインズ・ゲート',
    romajiTitle: 'Steins;Gate',
    synopsis: 'Rintaro Okabe, ilmuwan gila eksentrik, tanpa sengaja menemukan cara mengirim pesan teks ke masa lalu menggunakan oven microwave yang dimodifikasi. Eksperimen ini memicu rangkaian manipulasi garis waktu yang membawa konsekuensi maut.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx9253-tIUXF2gfU8Sg.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/n9253-JIhmKgBKsWUN.jpg',
    score: 8.9,
    scoredBy: 1400000,
    rank: 3,
    popularity: 18,format: 'TV',
    
    status: 'Completed',
    episodesCount: 24,
    duration: '24 min per ep',
    season: 'Spring',
    year: 2011,
    genres: ['Drama', 'Sci-Fi', 'Suspense', 'Psychological'],
    studios: ['White Fox'],
    ratingBadge: '17+',
    episodes: generateEpisodes(18, 'Steins;Gate', 24, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/n9253-JIhmKgBKsWUN.jpg')
  },
  {
    id: 19,
    title: 'Spy x Family Season 2',
    japaneseTitle: 'SPY×FAMILY Season 2',
    romajiTitle: 'SPY×FAMILY Season 2',
    synopsis: 'Mata-mata handal Twilight harus membangun keluarga samaran demi misi perdamaian dunia. Tanpa ia ketahui, istri yang dinikahinya adalah pembunuh bayaran ulung, dan putri angkatnya adalah gadis telepati yang bisa membaca pikiran.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b158927-lfO85WVguYgc.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/158927-zXtbXUO5iKzX.jpg',
    score: 8,
    scoredBy: 590000,
    rank: 22,
    popularity: 19,format: 'TV',
    
    status: 'Completed',
    episodesCount: 12,
    duration: '24 min per ep',
    season: 'Fall',
    year: 2023,
    genres: ['Action', 'Comedy', 'Slice of Life'],
    studios: ['WIT Studio', 'CloverWorks'],
    ratingBadge: '13+',
    episodes: generateEpisodes(19, 'Spy x Family', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/158927-zXtbXUO5iKzX.jpg')
  },
  {
    id: 20,
    title: 'Vinland Saga Season 2',
    japaneseTitle: 'ヴィンランド・サガ SEASON2',
    romajiTitle: 'VINLAND SAGA SEASON 2',
    synopsis: 'Thorfinn yang kehilangan tujuan hidup setelah kematian Askeladd kini bekerja sebagai budak di tanah pertanian Ketil. Di tengah kehampaan jiwanya, ia memulai perjalanan filosofis untuk memahami arti sejati dari seorang pejuang tanpa pedang.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx136430-gsBsJjA7hGh9.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/136430-ktoFZnyubhHg.jpg',
    score: 8.8,
    scoredBy: 460000,
    rank: 8,
    popularity: 20,format: 'TV',
    
    status: 'Completed',
    episodesCount: 24,
    duration: '24 min per ep',
    season: 'Winter',
    year: 2023,
    genres: ['Action', 'Adventure', 'Drama', 'Historical'],
    studios: ['MAPPA'],
    ratingBadge: '17+',
    episodes: generateEpisodes(20, 'Vinland Saga', 24, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/136430-ktoFZnyubhHg.jpg')
  },
  {
    id: 21,
    title: 'Violet Evergarden',
    japaneseTitle: 'ヴァイオレット・エヴァーガーデン',
    romajiTitle: 'Violet Evergarden',
    synopsis: 'Mantan tentara anak perempuan yang hanya mengenal medan perang kini bekerja sebagai Auto Memory Doll yang mengetik surat emosional bagi orang lain, demi mengungkap arti kata terakhir dari Mayor Gilbert: "Aku mencintaimu".',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21827-ubzq619ZA2E9.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21827-ROucgYiiiSpR.jpg',
    score: 8.5,
    scoredBy: 980000,
    rank: 16,
    popularity: 21,format: 'TV',
    
    status: 'Completed',
    episodesCount: 13,
    duration: '24 min per ep',
    season: 'Winter',
    year: 2018,
    genres: ['Drama', 'Fantasy', 'Slice of Life'],
    studios: ['Kyoto Animation'],
    ratingBadge: '13+',
    episodes: generateEpisodes(21, 'Violet Evergarden', 13, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/21827-ROucgYiiiSpR.jpg')
  },
  {
    id: 22,
    title: 'Wind Breaker',
    japaneseTitle: 'WIND BREAKER',
    romajiTitle: 'WIND BREAKER',
    synopsis: 'Haruka Sakura datang ke SMA Furin dengan satu tujuan: mengalahkan semua orang dan menjadi yang terkuat di puncak sekolah preman. Namun ia terkejut saat mengetahui murid Furin justru menjadi pelindung kota yang dicintai warga.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx163270-wboZJp0ybwVK.jpg',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/163270-fcjrqp3iKWdb.jpg',
    score: 7.7,
    scoredBy: 180000,
    rank: 45,
    popularity: 22,format: 'TV',
    
    status: 'Completed',
    episodesCount: 12,
    duration: '23 min per ep',
    season: 'Spring',
    year: 2024,
    genres: ['Action', 'Delinquents', 'School'],
    studios: ['CloverWorks'],
    ratingBadge: '13+',
    episodes: generateEpisodes(22, 'Wind Breaker', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/163270-fcjrqp3iKWdb.jpg')
  },
  {
    id: 23,
    title: 'Yu Yu Hakusho',
    japaneseTitle: '幽☆遊☆白書',
    romajiTitle: 'Yuu☆Yuu☆Hakusho',
    synopsis: 'Yusuke Urameshi, remaja pembuat onar berusia 14 tahun, tewas setelah menyelamatkan seorang anak kecil dari tabrakan mobil. Tindakan altruistiknya mengejutkan Dunia Roh, dan ia diberi kesempatan hidup kembali sebagai Detektif Roh.',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx392-z90299zIvYmx.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/392-nbB6cBnhHOFb.jpg',
    score: 8.3,
    scoredBy: 580000,
    rank: 25,
    popularity: 23,format: 'TV',
    
    status: 'Completed',
    episodesCount: 112,
    duration: '24 min per ep',
    season: 'Fall',
    year: 1992,
    genres: ['Action', 'Comedy', 'Supernatural', 'Martial Arts'],
    studios: ['Pierrot'],
    ratingBadge: '13+',
    episodes: generateEpisodes(23, 'Yu Yu Hakusho', 24, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/392-nbB6cBnhHOFb.jpg')
  },
  {
    id: 24,
    title: 'Zom 100: Bucket List of the Dead',
    japaneseTitle: 'ゾン100～ゾンビになるまでにしたい100のこと～',
    romajiTitle: 'Zom 100: Zombie ni Naru Made ni Shitai 100 no Koto',
    synopsis: 'Akira Tendo menderita selama 3 tahun bekerja di perusahaan eksploitatif yang menghancurkan jiwanya. Ketika wabah zombie mendadak menghancurkan Tokyo, alih-alih panik, Akira justru bersorak gembira karena tidak perlu lagi masuk kantor!',
    posterImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx159831-cJUNqCqzuApc.png',
    coverImage: 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/159831-FWfdyqpxhLli.jpg',
    score: 7.6,
    scoredBy: 240000,
    rank: 52,
    popularity: 24,format: 'TV',
    
    status: 'Completed',
    episodesCount: 12,
    duration: '24 min per ep',
    season: 'Summer',
    year: 2023,
    genres: ['Action', 'Comedy', 'Horror', 'Supernatural'],
    studios: ['BUG FILMS'],
    ratingBadge: '17+',
    episodes: generateEpisodes(24, 'Zom 100', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/banner/159831-FWfdyqpxhLli.jpg')
  },
  {
    id: 101,
    anilistId: 131573,
    malId: 48561,
    title: "JUJUTSU KAISEN 0",
    japaneseTitle: "呪術廻戦 0",
    romajiTitle: "Jujutsu Kaisen 0",
    synopsis: "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enr",
    posterImage: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx131573-rpl82vDEDRm6.jpg",
    coverImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/131573-3veuVz5p0z2I.jpg",
    score: 8.3,
    scoredBy: 350000,
    rank: 10,
    popularity: 5,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    duration: "1j 45m (105 min)",
    year: 2021,
    genres: ["Action","Supernatural"],
    studios: ["MAPPA"],
    ratingBadge: '13+',
    episodes: generateMovieEpisode(101, "JUJUTSU KAISEN 0", "1j 45m (105 min)", "https://s4.anilist.co/file/anilistcdn/media/anime/banner/131573-3veuVz5p0z2I.jpg", "2docezZl574")
  },
  {
    id: 102,
    anilistId: 21519,
    malId: 32281,
    title: "Kimi no Na wa. (Your Name)",
    japaneseTitle: "君の名は。",
    romajiTitle: "Kimi no Na wa.",
    synopsis: "Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture. One day, Mitsuha",
    posterImage: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21519-SUo3ZQuCbYhJ.png",
    coverImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21519-1ayMXgNlmByb.jpg",
    score: 8.6,
    scoredBy: 350000,
    rank: 10,
    popularity: 5,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    duration: "1j 47m (107 min)",
    year: 2016,
    genres: ["Drama","Romance","Supernatural"],
    studios: ["CoMix Wave"],
    ratingBadge: '13+',
    episodes: generateMovieEpisode(102, "Kimi no Na wa. (Your Name)", "1j 47m (107 min)", "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21519-1ayMXgNlmByb.jpg", "k4xGqY5IDBE")
  },
  {
    id: 103,
    anilistId: 20954,
    malId: 28851,
    title: "Koe no Katachi (A Silent Voice)",
    japaneseTitle: "聲の形",
    romajiTitle: "Koe no Katachi",
    synopsis: "After transferring into a new school, a deaf girl, Shouko Nishimiya, is bullied by the popular Shouya Ishida. As Shouya continues to bully Shouko, the class turns its back on him. Shouko transfers and Shouya grows up as an outcast. Alone and depressed, the regretful Shouya finds Shouko to make amends. (Source: Eleven Arts)",
    posterImage: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20954-sYRfE5jQRtSB.jpg",
    coverImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20954-f30bHMXa5Qoe.jpg",
    score: 8.8,
    scoredBy: 350000,
    rank: 10,
    popularity: 5,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    duration: "2j 10m (130 min)",
    year: 2016,
    genres: ["Drama","Romance","Slice of Life"],
    studios: ["Kyoto Animation"],
    ratingBadge: '13+',
    episodes: generateMovieEpisode(103, "Koe no Katachi (A Silent Voice)", "2j 10m (130 min)", "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20954-f30bHMXa5Qoe.jpg", "Sy4bPCuzfiQ")
  },
  {
    id: 104,
    anilistId: 112151,
    malId: 40456,
    title: "Demon Slayer: Mugen Train (Movie)",
    japaneseTitle: "鬼滅の刃 無限列車編",
    romajiTitle: "Kimetsu no Yaiba: Mugen Ressha-hen",
    synopsis: "This Demon Slayer movie sees Tanjiro Kamado and friends from the Demon Slayer corps board the Infinity Train on a new mission to investigate a mysterious series of disappearances, perpetrated by a demon who has been tormenting people and killing the demon slayers who oppose it.",
    posterImage: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx112151-1qlQwPB1RrJe.png",
    coverImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/112151-eHCBz19nf2yC.jpg",
    score: 8.4,
    scoredBy: 350000,
    rank: 10,
    popularity: 5,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    duration: "1j 57m (117 min)",
    year: 2020,
    genres: ["Action","Adventure","Drama","Fantasy","Mystery","Supernatural"],
    studios: ["ufotable"],
    ratingBadge: '13+',
    episodes: generateMovieEpisode(104, "Demon Slayer: Mugen Train (Movie)", "1j 57m (117 min)", "https://s4.anilist.co/file/anilistcdn/media/anime/banner/112151-eHCBz19nf2yC.jpg", "23riEOmDOgM")
  },
  {
    id: 105,
    anilistId: 142770,
    malId: 50594,
    title: "Suzume no Tojimari",
    japaneseTitle: "すずめの戸締まり",
    romajiTitle: "Suzume no Tojimari",
    synopsis: "The story follows Suzume, a 17-year-old girl from a quiet Kyushu town who meets a young man looking for a door. They find a door within ruins in the mountain, and Suzume opens it. Soon, more doors begin to open around Japan, bringing disasters from the other side. The film depicts Suzume's liberation and growth, as she closes the doors that are cau",
    posterImage: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx142770-dDaDIRnsv5jN.jpg",
    coverImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/142770-YgESt2HJXlNg.jpg",
    score: 8.1,
    scoredBy: 350000,
    rank: 10,
    popularity: 5,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    duration: "2j 1m (121 min)",
    year: 2022,
    genres: ["Adventure","Fantasy","Mystery","Supernatural"],
    studios: ["CoMix Wave"],
    ratingBadge: '13+',
    episodes: generateMovieEpisode(105, "Suzume no Tojimari", "2j 1m (121 min)", "https://s4.anilist.co/file/anilistcdn/media/anime/banner/142770-YgESt2HJXlNg.jpg", "g0JMPkn7Wuo")
  },
  {
    id: 106,
    anilistId: 106286,
    malId: 38826,
    title: "Weathering With You (Tenki no Ko)",
    japaneseTitle: "天気の子",
    romajiTitle: "Tenki no Ko",
    synopsis: "High school student Hodaka leaves his home on an isolated island and moves to Tokyo, but he immediately becomes broke. He lives his days in isolation, but finally finds a job as a writer for a shady occult magazine. After he starts his job, the weather has been rainy day after day. In a corner of the crowded and busy city, Hodaka meets a young woma",
    posterImage: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx106286-5COcpd0J9VbL.png",
    coverImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/106286-3oKwiwjd7Wkm.jpg",
    score: 8.1,
    scoredBy: 350000,
    rank: 10,
    popularity: 5,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    duration: "1j 55m (115 min)",
    year: 2019,
    genres: ["Drama","Romance","Slice of Life","Supernatural"],
    studios: ["CoMix Wave"],
    ratingBadge: '13+',
    episodes: generateMovieEpisode(106, "Weathering With You (Tenki no Ko)", "1j 55m (115 min)", "https://s4.anilist.co/file/anilistcdn/media/anime/banner/106286-3oKwiwjd7Wkm.jpg", "Q6iK6DjV_iE")
  },
  {
    id: 107,
    anilistId: 141902,
    malId: 50410,
    title: "One Piece Film: RED",
    japaneseTitle: "ONE PIECE FILM RED",
    romajiTitle: "ONE PIECE FILM: RED",
    synopsis: "An almighty voice. With fiery red locks. The story takes place on an island where Uta, the world’s favorite diva, performs for the first time in public. Uta’s singing voice, which she sings with while concealing her true identity, has been described as “otherworldly,” and while the venue is filled with the Straw Hats led by Luffy, pirates, navy, an",
    posterImage: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx141902-fTyoTk8F8qOl.jpg",
    coverImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/141902-SvnRSXnN7DWC.jpg",
    score: 7.8,
    scoredBy: 350000,
    rank: 10,
    popularity: 5,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    duration: "1j 55m (115 min)",
    year: 2022,
    genres: ["Action","Adventure","Comedy","Drama","Fantasy","Music"],
    studios: ["Toei Animation"],
    ratingBadge: '13+',
    episodes: generateMovieEpisode(107, "One Piece Film: RED", "1j 55m (115 min)", "https://s4.anilist.co/file/anilistcdn/media/anime/banner/141902-SvnRSXnN7DWC.jpg", "YAN45KAL5lg")
  },
  {
    id: 108,
    anilistId: 199,
    malId: 199,
    title: "Spirited Away (Sen to Chihiro)",
    japaneseTitle: "千と千尋の神隠し",
    romajiTitle: "Sen to Chihiro no Kamikakushi",
    synopsis: "On the way to their new home, 10-year-old Chihiro Ogino's family stumbles upon a deserted theme park. Intrigued, the family investigates the park, though unbeknownst to them, it is secretly inhabited by spirits who sleep by day and appear at night. When Chihiro's mother and father eat food from a restaurant in the street, angry spirits turn them in",
    posterImage: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx199-sWefXJvXkDOb.jpg",
    coverImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/199-Sm2RU5PSqw7T.jpg",
    score: 8.6,
    scoredBy: 350000,
    rank: 10,
    popularity: 5,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    duration: "2j 5m (125 min)",
    year: 2001,
    genres: ["Adventure","Drama","Fantasy","Supernatural"],
    studios: ["Studio Ghibli"],
    ratingBadge: '13+',
    episodes: generateMovieEpisode(108, "Spirited Away (Sen to Chihiro)", "2j 5m (125 min)", "https://s4.anilist.co/file/anilistcdn/media/anime/banner/199-Sm2RU5PSqw7T.jpg", "ByXuk9QqQkk")
  },
  {
    id: 109,
    anilistId: 431,
    malId: 431,
    title: "Howl's Moving Castle",
    japaneseTitle: "ハウルの動く城",
    romajiTitle: "Howl no Ugoku Shiro",
    synopsis: "Sophie, a quiet girl working in a hat shop, finds her life thrown into turmoil when she is literally swept off her feet by a handsome but mysterious wizard named Howl. The vain and vengeful Witch of the Waste, jealous of their friendship, puts a spell on Sophie. In a life-changing adventure, Sophie climbs aboard Howl's magnificent flying castle and",
    posterImage: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx431-o8Lj3XkjHm2k.jpg",
    coverImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/431-fLBlvTgdqLCz.jpg",
    score: 8.5,
    scoredBy: 350000,
    rank: 10,
    popularity: 5,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    duration: "1j 59m (119 min)",
    year: 2004,
    genres: ["Adventure","Drama","Fantasy","Romance"],
    studios: ["Studio Ghibli"],
    ratingBadge: '13+',
    episodes: generateMovieEpisode(109, "Howl's Moving Castle", "1j 59m (119 min)", "https://s4.anilist.co/file/anilistcdn/media/anime/banner/431-fLBlvTgdqLCz.jpg", "iwROgK94zcM")
  },
  {
    id: 110,
    anilistId: 109979,
    malId: 36699,
    title: "The Boy and the Heron",
    japaneseTitle: "君たちはどう生きるか",
    romajiTitle: "Kimitachi wa Dou Ikiru ka",
    synopsis: "While the Second World War rages, the teenage Mahito, haunted by his mother’s tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy’s mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray hero",
    posterImage: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx109979-BRHXpBkCw4oc.jpg",
    coverImage: "https://s4.anilist.co/file/anilistcdn/media/anime/banner/109979-eeUPfBXMEflG.jpg",
    score: 7.7,
    scoredBy: 350000,
    rank: 10,
    popularity: 5,
    format: 'Movie',
    status: 'Completed',
    episodesCount: 1,
    duration: "2j 4m (124 min)",
    year: 2023,
    genres: ["Adventure","Drama","Fantasy","Supernatural"],
    studios: ["Studio Ghibli"],
    ratingBadge: '13+',
    episodes: generateMovieEpisode(110, "The Boy and the Heron", "2j 4m (124 min)", "https://s4.anilist.co/file/anilistcdn/media/anime/banner/109979-eeUPfBXMEflG.jpg", "f7EDFdA10pg")
  }
];

export const GENRES_LIST = [
  'All Genres',
  'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Fantasy',
  'Gore',
  'Historical',
  'Isekai',
  'Music',
  'Mystery',
  'Psychological',
  'Romance',
  'Sci-Fi',
  'School',
  'Shounen',
  'Slice of Life',
  'Supernatural',
  'Suspense'
];
